accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='list'),
    path('create/', views.articles_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.articles_detail, name='detail'),
]

blog/urls.py
from django.urls import path, include
from . import views
from articles import views as articles_views


app_name = 'blog'

urlpatterns = [
    path('articles/', include('articles.urls',
                              namespace='articles'), name='articles'),
    path('accounts/', include('accounts.urls',
                              namespace='accounts'), name='accounts'),
    path('', articles_views.articles_list, name='index'),
    path('aboutUs/', views.whoAmI, name='aboutUs'),
]

blog_api/urls.py
from django.urls import path

app_name = 'blog_api'

urlpatterns = [
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('api/', include('blog_api.urls', namespace='blog_api')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:80] + '...'

blog/models.py
from django.db import models

# Create your models here.

blog_api/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django.forms import ModelForm
from . import models


class CreateArticle(ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blog:articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles_list.html', {'articles': articles})


def articles_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'article_detail.html', {'article': article})


@login_required(login_url='/accounts/login/')
def articles_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('blog:articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'article_create.html', {'form': form})

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader


def index(request):
    return render(request, 'index.html')


def whoAmI(request):
    template = loader.get_template('aboutUs.html')
    return HttpResponse(template.render())

blog_api/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h2> Sign up </h2>
<form class="site-form" action="{% url 'blog:accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h2> Sign up </h2>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

articles/templates/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h2>Create a New Article</h2>
    <form class="create-article" action="{% url 'blog:articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %}

articles/templates/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Articles list</h1>
<br><br>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <a href="{% url 'blog:articles:detail' slug=article.slug %}">
            <h2>{{ article.title }}</h2>
        </a>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <br><br>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/blog/aboutUs.html
<html>

<head>
    <title>About Us</title>
</head>

<body>
    <h1>My name is Naruto</h1>
</body>

</html>

templates/blog/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Articles</title>
</head>

<body>
    <header>
        <h1><a href="{% url 'blog:index' %}"><img src="{% static 'logo.png' %}" alt="logo" /></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'blog:accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">
                            Logout
                        </button>
                    </form>
                </li>
                <li><a href="{% url 'blog:articles:create' %}">New Article</a></li>
                {% else %}
                <li><a href="{% url 'blog:accounts:login' %}">Login</a></li>
                <li><a href="{% url 'blog:accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
        <br><br>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

templates/blog/index.html
<html>

<body>
    <h1>Madi loshara </h1>
</body>

</html>